
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminOperationsService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/DVL/admin?wsdl")
public class AdminOperationsService
    extends Service
{

    private final static URL ADMINOPERATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINOPERATIONSSERVICE_EXCEPTION;
    private final static QName ADMINOPERATIONSSERVICE_QNAME = new QName("http://server/", "AdminOperationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DVL/admin?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINOPERATIONSSERVICE_WSDL_LOCATION = url;
        ADMINOPERATIONSSERVICE_EXCEPTION = e;
    }

    public AdminOperationsService() {
        super(__getWsdlLocation(), ADMINOPERATIONSSERVICE_QNAME);
    }

    public AdminOperationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINOPERATIONSSERVICE_QNAME, features);
    }

    public AdminOperationsService(URL wsdlLocation) {
        super(wsdlLocation, ADMINOPERATIONSSERVICE_QNAME);
    }

    public AdminOperationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINOPERATIONSSERVICE_QNAME, features);
    }

    public AdminOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminOperationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminOperations
     */
    @WebEndpoint(name = "AdminOperationsPort")
    public AdminOperations getAdminOperationsPort() {
        return super.getPort(new QName("http://server/", "AdminOperationsPort"), AdminOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminOperations
     */
    @WebEndpoint(name = "AdminOperationsPort")
    public AdminOperations getAdminOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "AdminOperationsPort"), AdminOperations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINOPERATIONSSERVICE_EXCEPTION!= null) {
            throw ADMINOPERATIONSSERVICE_EXCEPTION;
        }
        return ADMINOPERATIONSSERVICE_WSDL_LOCATION;
    }

}
